---

- hosts: workstation
  roles:
    - common
    - { role: workstation, when: is_workstation }

- hosts: gw
  roles:
    - common
    - { role: gw, when: is_gw }

- hosts: storage
  roles:
    - common
    - { role: storage, when: is_storage }

- hosts: cloud
  roles:
    - common
    - { role: devel }
    - { role: testing }
