---

- name: adjust timezone
  when: ansible_os_family == "OpenBSD"
  become: yes
  become_method: doas
  file:
    src: /usr/share/zoneinfo/"{{timezone}}"
    dest: /etc/localtime
    owner: root
    group: wheel
    state: link
    force: yes
