---

- name: enable services on boot
  when: ansible_os_family == "OpenBSD"
  become: yes
  become_method: doas
  service:
    name: "{{item}}"
    state: started
    enabled: True
  with_items:
    - cron
    - dhcpd
    - nsd
    - ntpd
    - pflogd
    - slaacd
    - smtpd
    - sshd
    - syslogd
    - unbound
