---

- name: enable services on boot
  when: ansible_os_family == "OpenBSD"
  become: yes
  become_method: doas
  service:
    name: "{{item}}"
    state: started
    enabled: True
  with_items:
    - cron
    - dkimproxy_in
    - dkimproxy_out
    - httpd
    - isakmpd
    - monit
    - npppd
    - nsd
    - ntpd
    - pflogd
    - slaacd
    - slowcgi
    - smtpd
    - sshd
    - syslogd
